##################################################################
####### users / roles
##################################################################


- name: add oracle groups
  become: yes
  become_method: sudo
  become_user: root

  group: 
    name={{ item.name }} 
  with_items:
      - { name: 'oinstall' }
      - { name: 'dba'}


- name: add oracle user
  become: yes
  become_method: sudo
  become_user: root

  user: 
      name=oracle 
      group=oinstall 
      groups=dba 
      home=/home/oracle 
      createhome=no
      password={{ 'oracle'|password_hash('sha512', 'cRhJP88S') }}

- name: create oracle home 
  become: yes
  become_method: sudo
  become_user: root

  file: 
      path=/home/oracle 
      state=directory 
      owner=oracle 
      group=dba

##################################################################
####### /etc/sysctl.conf
##################################################################

- name: Change kernel parameters
  become: yes
  become_method: sudo
  become_user: root

  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel_params }}"
  register: resultUpdateKernel


- name: restart sysctl
  become: yes
  become_method: sudo
  become_user: root

  shell: sysctl -p
  when: resultUpdateKernel.changed


 
##################################################################
############# config /etc/security/limits.conf ###################
##################################################################

- name: check desc in /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     line='#ORACLE_DB params' 
     backup=yes 
  register: resultAddLineLimits


- name: add desc to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp=^#ORACLE_DB
     line='\n#ORACLE_DB params' 
  when: resultAddLineLimits.changed


- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle soft nofile'
     line='oracle soft nofile 65536'

- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle hard nofile'
     line='oracle hard nofile 65536'

- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle soft nproc'
     line='oracle soft nproc 16384'

- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle hard nproc'
     line='oracle hard nproc 16384'

- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle soft stack'
     line='oracle soft stack 10240'

- name: add line to /etc/security/limits.conf
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/security/limits.conf
     regexp='^oracle hard stack'
     line='oracle hard stack 32768'


##################################################################
#############      /etc/pam.d/login            ###################
##################################################################

- name: add line to /etc/pam.d/login
  become: yes
  become_method: sudo
  become_user: root

  lineinfile: 
     dest=/etc/pam.d/login
     regexp='^session required pam_limits.so'
     line='session required pam_limits.so'



##################################################################
#############      /etc/profile                ###################
##################################################################

- name: add to /etc/profile 
  become: yes
  become_method: sudo
  become_user: root

  blockinfile:
    path: /etc/profile
    marker: "# {mark} ORACLE DB params"
    block: |
      if [ $USER = "oracle" ] ; then
        if [ $SHELL = "/bin/ksh" ]; then
          ulimit -p 16384
          ulimit -n 65536
        else
          ulimit -u 16384 -n 65536
        fi
        umask 022
      fi


##################################################################
#############  install packages                ###################
##################################################################

- import_tasks: redhat.yml
  become: yes
  become_method: sudo
  become_user: root
  when: ansible_distribution|lower == 'redhat'

- import_tasks: debian.yml
  become: yes
  become_method: sudo
  become_user: root
  when: ansible_distribution|lower == 'debian'

- import_tasks: sles.yml
  become: yes
  become_method: sudo
  become_user: root
  when: ansible_distribution|lower == 'sles'


##################################################################
#############      /etc/ssh/sshd_config        ###################
##################################################################

- name: add to /etc/ssh/sshd_config 
  become: yes
  become_method: sudo
  become_user: root

  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ORACLE DB params"
    block: |
      X11Forwarding yes
      X11DisplayOffset 10
      X11UseLocalhost yes
  register: resultUpdateSshd

- name: Restart sshd
  become: yes
  become_method: sudo
  become_user: root

  service:
    name: 'sshd'
    state: 'restarted'
  when: resultUpdateSshd.changed


